app:                               ### блок про деплой ### 
  name: log-message                  # название приложения
  standName:                       # полезная переменная для выкатки на разные стенды
  secretName: hello-secret         # имя файла с секретами
  branch: develop                  # полезная переменная для передачи в аннтоцию имени ветки
  replicas: 1                      # количество реплик для приложения

image:                             ### блок про образ ###
  app: myregistry:5000/log-message-processor            # имя образа
  tag:  latest                     # тег образа
  
service:                           ### блок про сервис ###
  internalPort: 8083                 # порт внутренний
  externalPort: 8083                 # порт внешний

redis:
  host: "lab1"
  port: "6379"
  log_channel: "log_channel"

zipkin: 
  host: "lab1"
  port: "9411"
  url: "http://lab1:9411/api/v2/spans"

config:                            
  env: "456"                       # здесь могла бы быть ваша переменная для конфигмапы

limits:                            ### блок про лимиты ###
  cpu: "2"                         # 2 ядра, если приложение потребует больше, оно будет тормозить
  memory: "4Gi"                    # 4Гб ОЗУ, если приложение потребует больше, придёт ООМ killer :)

requests:                          ### блок про реквесты (минимальные значения для запуска приложения) ###
  cpu: "100m"                      # 0.1 ядра, 260Мб ОЗУ - тут мы указываем, что приложению необходимо минимум вот столько
  memory: "260Mi"                  # соответственно sheduler назначит под на ноду, где есть столько ресурсов

hpa:                               ### блок про hpa ###
  enable: false                     # включён если true
  min_pod_count: 2                 # минимальное количество реплик
  max_pod_count: 6                 # максимальное количество реплик
  averageUtilization: 50           # средняя нагрузка на процессор для запуска новой реплики

pdb:                               ### блок про hpa ###
  enable: false                     # включён если true
  minAvailable: 2                  # минимальное количество доступных реплик